### ISSUE TITLE
Are dynamic attributes supported?

### ISSUE THREAD

**Issue by schalk-b** [vidhanio/hypertext#34]
This comment on maud explains my use-case well https://github.com/lambda-fairy/maud/issues/240#issuecomment-1193347942

**Comment by vidhanio** [comment]
unfortunately not @schalk-b. the attributes being type-checked (and as such, not dynamic) is an important part of hypertext. Maybe there is some middle ground that me or someone else could attempt to come up with?

**Comment by vidhanio** [comment]
@jgayfer yes it is, via this syntax:

```rust
maud! {
	div id=[maybe_id] {
		// Children
	}
}
```
