### ISSUE TITLE
Custom Attribute with dash

### ISSUE THREAD

**Issue by ssipos90** [vidhanio/hypertext#36]
Hello,

Cool library!

I was trying to add support for htmx attributes which use `hx-*` convention.

I added
```rust
#[allow(dead_code, non_upper_case_globals)]
pub trait HtmxAttributes: GlobalAttributes {
    const hx_get: Attribute = Attribute;
    const hx_post: Attribute = Attribute;
    const hx_target: Attribute = Attribute;
}

impl<T: GlobalAttributes> HtmxAttributes for T {}
```
but those end up with underscores in the generated html.

Any workarounds?

Thanks!

**Comment by ssipos90** [comment]
never mind, copilot "helped" me in making a typo.

**Comment by vidhanio** [comment]
Sorry I missed this, I'm happy to see it resolved itself though. Thank you for using hypertext!
